[project]
name = "mta-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.9.0",
    "django>=5.2.7",
    "django-filter>=25.2",
    "djangorestframework>=3.16.1",
]
